services:
  apple-dl-ui:
    build: ./frontend
    container_name: apple-dl-ui
    image: f8ith/apple-dl-ui:stable
    ports:
      - "0.0.0.0:6887:6887"

  apple-dl-server:
    build: ./backend
    container_name: apple-dl-server
    image: f8ith/apple-dl-server:stable
    volumes:
      - ./appledl-docker:/config
      - /mnt/media-server/ingest/music:/downloads
    ports:
      - "0.0.0.0:8000:8000"

