/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DiscordBotRouteImport } from './routes/discord-bot'
import { Route as IndexRouteImport } from './routes/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordBotRoute = DiscordBotRouteImport.update({
  id: '/discord-bot',
  path: '/discord-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discord-bot': typeof DiscordBotRoute
  '/jobs': typeof JobsRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discord-bot': typeof DiscordBotRoute
  '/jobs': typeof JobsRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discord-bot': typeof DiscordBotRoute
  '/jobs': typeof JobsRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discord-bot' | '/jobs' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discord-bot' | '/jobs' | '/search'
  id: '__root__' | '/' | '/discord-bot' | '/jobs' | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscordBotRoute: typeof DiscordBotRoute
  JobsRoute: typeof JobsRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-bot': {
      id: '/discord-bot'
      path: '/discord-bot'
      fullPath: '/discord-bot'
      preLoaderRoute: typeof DiscordBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscordBotRoute: DiscordBotRoute,
  JobsRoute: JobsRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
