import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/openapi-schema"; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: "/"
});


export const $api = createClient(fetchClient);

export const PAGESIZE = 25;